/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exameninfra;

import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vargas
 */
public class Administrativo extends javax.swing.JFrame {

    /**
     * Creates new form Administrativo
     */
    public boolean fetch;
    public boolean placement;
    public int replacement;
    public boolean cleaning;
    public boolean management_size;
    public boolean replacement_scope;
    public int sys_size;
    public int sys_memory;
    public int sys_process;
    public int sys_commands;

    public Administrativo() {
        initComponents();
        //sel_replacement_scope.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sel_fetch = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        sel_placement = new javax.swing.JComboBox();
        label_address_direct_type = new javax.swing.JLabel();
        sel_replacement_scope = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        sel_size = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        sel_replacement = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sel_cleaning = new javax.swing.JComboBox();
        jSeparator4 = new javax.swing.JSeparator();
        label_address_direct_type1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_Continue = new javax.swing.JButton();
        label_address_direct_type2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSpinnerSize = new javax.swing.JSpinner();
        jSpinnerMemory = new javax.swing.JSpinner();
        jSpinnerProcess = new javax.swing.JSpinner();
        label_address_direct_type3 = new javax.swing.JLabel();
        jSpinnerCommands = new javax.swing.JSpinner();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración del Sistema de Memoria Virtual");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(450, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(490, 410));

        jSeparator1.setForeground(new java.awt.Color(98, 156, 68));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(98, 156, 68));
        jLabel1.setText("Policies");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Fetch:");

        sel_fetch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Demand", "Prepaging" }));
        sel_fetch.setToolTipText("");
        sel_fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel_fetchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Placement:");

        sel_placement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First Available", "Next Available" }));
        sel_placement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel_placementActionPerformed(evt);
            }
        });

        label_address_direct_type.setBackground(new java.awt.Color(255, 255, 255));
        label_address_direct_type.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_address_direct_type.setText("Replacement Scope:");
        label_address_direct_type.setOpaque(true);

        sel_replacement_scope.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Global", "Local" }));
        sel_replacement_scope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel_replacement_scopeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Size:");

        sel_size.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fixed", "Variable" }));
        sel_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel_sizeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Replacement:");

        sel_replacement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FIFO", "MRU", "LRU", "Clock" }));
        sel_replacement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel_replacementActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(98, 156, 68));
        jLabel7.setText("System Parameters");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Cleaning:");

        sel_cleaning.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Demand", "Pre-cleaning" }));
        sel_cleaning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel_cleaningActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(98, 156, 68));

        label_address_direct_type1.setBackground(new java.awt.Color(255, 255, 255));
        label_address_direct_type1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_address_direct_type1.setText("Total memory (MB):");
        label_address_direct_type1.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Page size (KBs):");

        btn_Continue.setBackground(new java.awt.Color(98, 156, 68));
        btn_Continue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_Continue.setForeground(new java.awt.Color(0, 102, 0));
        btn_Continue.setText("Continuar");
        btn_Continue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ContinueActionPerformed(evt);
            }
        });

        label_address_direct_type2.setBackground(new java.awt.Color(255, 255, 255));
        label_address_direct_type2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_address_direct_type2.setText("Maximum processes:");
        label_address_direct_type2.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(98, 156, 68));
        jLabel2.setText("Resident Set Management");

        jSeparator2.setForeground(new java.awt.Color(98, 156, 68));

        label_address_direct_type3.setBackground(new java.awt.Color(255, 255, 255));
        label_address_direct_type3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_address_direct_type3.setText("Commands for visualization:");
        label_address_direct_type3.setOpaque(true);

        jSeparator5.setForeground(new java.awt.Color(98, 156, 68));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label_address_direct_type)
                                            .addComponent(jLabel13))
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sel_placement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sel_fetch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sel_replacement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sel_cleaning, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sel_size, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sel_replacement_scope, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_address_direct_type2)
                                    .addComponent(label_address_direct_type1)
                                    .addComponent(jLabel14)
                                    .addComponent(label_address_direct_type3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinnerMemory)
                                    .addComponent(jSpinnerSize)
                                    .addComponent(jSpinnerProcess)
                                    .addComponent(jSpinnerCommands, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btn_Continue, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel_fetch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel_placement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel_replacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel_cleaning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sel_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sel_replacement_scope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_address_direct_type))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_address_direct_type1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_address_direct_type2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCommands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_address_direct_type3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Continue, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ContinueActionPerformed
        System.out.println("Iniciando configuraciones");
//        int n = Integer.parseInt(number_process.getValue().toString());
        fetch = (sel_fetch.getSelectedItem().equals("Demand")) ? true : false;
        placement = (sel_placement.getSelectedItem().equals("First Available")) ? true : false;
        replacement = sel_replacement.getSelectedIndex();
        cleaning = (sel_size.getSelectedItem().equals("Demand")) ? true : false;
        management_size = (sel_size.getSelectedItem().equals("Fixed")) ? true : false;
        replacement_scope = (sel_replacement_scope.getSelectedItem().equals("Global")) ? true : false;
        sys_size = (Integer) jSpinnerSize.getValue();
        sys_memory = (Integer) jSpinnerMemory.getValue();
        sys_process = (Integer) jSpinnerProcess.getValue();
        sys_commands = (Integer) jSpinnerCommands.getValue();
        System.out.println(" " + fetch + " " + placement + " " + replacement + " " + cleaning + " " + management_size + " " + replacement_scope + " " + sys_size + " " + sys_memory + " " + sys_process + " " + sys_commands);
        //boolean format_type_b = (format_type.getSelectedItem().equals("Fijo")) ? true : false;
        if(0< sys_size  && 0< sys_memory && 0< sys_process && 0< sys_commands){
            CargarArchivos cargar_archivos = new CargarArchivos();
            cargar_archivos.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(new JFrame(), "Error en la configuración", "Mensaje",
        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ContinueActionPerformed

    private void sel_cleaningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_cleaningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sel_cleaningActionPerformed

    private void sel_replacementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_replacementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sel_replacementActionPerformed

    private void sel_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_sizeActionPerformed
        if (sel_size.getSelectedItem().equals("Variable")) {
            sel_replacement_scope.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Local"}));
        } else {
            sel_replacement_scope.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Global", "Local"}));
        }
    }//GEN-LAST:event_sel_sizeActionPerformed

    private void sel_replacement_scopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_replacement_scopeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sel_replacement_scopeActionPerformed

    private void sel_placementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_placementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sel_placementActionPerformed

    private void sel_fetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_fetchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sel_fetchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Administrativo admin = new Administrativo();
                admin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Continue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSpinner jSpinnerCommands;
    private javax.swing.JSpinner jSpinnerMemory;
    private javax.swing.JSpinner jSpinnerProcess;
    private javax.swing.JSpinner jSpinnerSize;
    private javax.swing.JLabel label_address_direct_type;
    private javax.swing.JLabel label_address_direct_type1;
    private javax.swing.JLabel label_address_direct_type2;
    private javax.swing.JLabel label_address_direct_type3;
    private javax.swing.JComboBox sel_cleaning;
    private javax.swing.JComboBox sel_fetch;
    private javax.swing.JComboBox sel_placement;
    private javax.swing.JComboBox sel_replacement;
    private javax.swing.JComboBox sel_replacement_scope;
    private javax.swing.JComboBox sel_size;
    // End of variables declaration//GEN-END:variables
}
